### ISSUE TITLE
Issue on FF 35.0.1

### ISSUE THREAD

**Issue by genuine-moes** [gonaumov/sexGangstersBizBot#2]
Add-on is described as corrupted on Firefox 35.0.1.
It's unfortunately unusable. :(
![module_broken](https://cloud.githubusercontent.com/assets/11043181/6227189/a56045d0-b69c-11e4-9a49-5612ef383ac1.png)

**Comment by gonaumov** [comment]
Hello.

I tested it on FireFox  35.0.1 and there is no problem with installation. 
You just do not download sexgangstersbizbot.xpi in the right way.
Try this url:
https://github.com/gonaumov/sexGangstersBizBot/raw/master/sexgangstersbizbot.xpi
After this just open it from File -> Open and it must be installed without problems. 
Write me back if there are problems.

**Comment by genuine-moes** [comment]
It works perfectly with your link! :+1: 

Thank you so much and nice job by the way!

**Comment by gonaumov** [comment]
Thank you. I added a direct link in the description to not have complaints with the same problem in the future. I will improve the bot when I have time. There will be other functions and improvements.
